### ISSUE TITLE
Register: shibboleth support

### ISSUE THREAD

**Issue by DanielPalafox** [ORCID/orcid-angular#206]

**Comment by DanielPalafox** [comment]
Currently, when you are linking your institutional account, if you don't have an orcid account if you press the register button, will be redirected to the register page with some parameters in the URL as name, email, etc and this will auto-fill the register form

**Comment by leomendoza123** [comment]
Rather than exposing the user email/name with GET parameters, it seems to be possible to get these values directly from the `/social/signinData.json` endpoint as @DanielPalafox does on 

https://github.com/ORCID/orcid-angular/blob/46abde39c7a1905bb7ee11c32070025486099368/src/app/link-account/pages/institutional-linking/institutional-linking.component.ts#L38-L51


Or even better reusing the data already fetched by that service
